### ISSUE TITLE
Gracefully handle lack of Pester 5.0

### ISSUE THREAD

**Issue by PrzemyslawKlys** [TylerLeonhardt/vscode-pester-test-adapter#27]
![image](https://user-images.githubusercontent.com/15063294/103337863-dc753100-4a7c-11eb-9226-58207e6f9ae9.png)

I've just synced my settings to computer without Pester 5.0 and error popped up. 

```
c:\Users\przemyslaw\.vscode\extensions\tylerleonhardt.vscode-pester-test-adapter-0.0.14\out\pesterTests.js:73
                        throw e;
                        ^

[SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at ChildProcess.<anonymous> (c:\Users\przemyslaw\.vscode\extensions\tylerleonhardt.vscode-pester-test-adapter-0.0.14\out\pesterTests.js:69:46)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)]
```

**Comment by TylerLeonhardt** [comment]
I can't repro this... but 0.0.15 is out and I get rid of every single `throw` in my code so this should be fixed
